### YamlMime:ManagedReference
items:
- uid: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig
  commentId: T:AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig
  id: TwitchRestApiConfig
  parent: AuxLabs.Twitch.Rest.Api
  children:
  - AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
  - AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
  langs:
  - csharp
  - vb
  name: TwitchRestApiConfig
  nameWithType: TwitchRestApiConfig
  fullName: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig
  type: Class
  source:
    remote:
      path: src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
      branch: main
      repo: https://github.com/AuxLabs/Twitch.git
    id: TwitchRestApiConfig
    path: ../src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
    startLine: 2
  assemblies:
  - AuxLabs.Twitch.Rest.Api
  namespace: AuxLabs.Twitch.Rest.Api
  syntax:
    content: public class TwitchRestApiConfig
    content.vb: Public Class TwitchRestApiConfig
  inheritance:
  - System.Object
  derivedClasses:
  - AuxLabs.Twitch.Rest.TwitchRestConfig
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
  commentId: P:AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
  id: ClientId
  parent: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig
  langs:
  - csharp
  - vb
  name: ClientId
  nameWithType: TwitchRestApiConfig.ClientId
  fullName: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
  type: Property
  source:
    remote:
      path: src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
      branch: main
      repo: https://github.com/AuxLabs/Twitch.git
    id: ClientId
    path: ../src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
    startLine: 5
  assemblies:
  - AuxLabs.Twitch.Rest.Api
  namespace: AuxLabs.Twitch.Rest.Api
  summary: ''
  example: []
  syntax:
    content: public string ClientId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ClientId As String
  overload: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId*
- uid: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
  commentId: P:AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
  id: ClientSecret
  parent: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig
  langs:
  - csharp
  - vb
  name: ClientSecret
  nameWithType: TwitchRestApiConfig.ClientSecret
  fullName: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
  type: Property
  source:
    remote:
      path: src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
      branch: main
      repo: https://github.com/AuxLabs/Twitch.git
    id: ClientSecret
    path: ../src/AuxLabs.Twitch.Rest.Api/TwitchRestApiConfig.cs
    startLine: 8
  assemblies:
  - AuxLabs.Twitch.Rest.Api
  namespace: AuxLabs.Twitch.Rest.Api
  summary: ''
  example: []
  syntax:
    content: public string ClientSecret { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ClientSecret As String
  overload: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret*
references:
- uid: AuxLabs.Twitch.Rest.Api
  commentId: N:AuxLabs.Twitch.Rest.Api
  href: AuxLabs.html
  name: AuxLabs.Twitch.Rest.Api
  nameWithType: AuxLabs.Twitch.Rest.Api
  fullName: AuxLabs.Twitch.Rest.Api
  spec.csharp:
  - uid: AuxLabs
    name: AuxLabs
    href: AuxLabs.html
  - name: .
  - uid: AuxLabs.Twitch
    name: Twitch
    href: AuxLabs.Twitch.html
  - name: .
  - uid: AuxLabs.Twitch.Rest
    name: Rest
    href: AuxLabs.Twitch.Rest.html
  - name: .
  - uid: AuxLabs.Twitch.Rest.Api
    name: Api
    href: AuxLabs.Twitch.Rest.Api.html
  spec.vb:
  - uid: AuxLabs
    name: AuxLabs
    href: AuxLabs.html
  - name: .
  - uid: AuxLabs.Twitch
    name: Twitch
    href: AuxLabs.Twitch.html
  - name: .
  - uid: AuxLabs.Twitch.Rest
    name: Rest
    href: AuxLabs.Twitch.Rest.html
  - name: .
  - uid: AuxLabs.Twitch.Rest.Api
    name: Api
    href: AuxLabs.Twitch.Rest.Api.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId*
  commentId: Overload:AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
  href: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId.html
  name: ClientId
  nameWithType: TwitchRestApiConfig.ClientId
  fullName: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret*
  commentId: Overload:AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
  href: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret.html
  name: ClientSecret
  nameWithType: TwitchRestApiConfig.ClientSecret
  fullName: AuxLabs.Twitch.Rest.Api.TwitchRestApiConfig.ClientSecret
memberLayout: SeparatePages
